title: Professor Yi Liu's Homepage
page-top-title: HKUST-gz EOAS 
top-section-bg-text: Land-Ocean-Groundwater Science Research Group
home-subtitle: Yi Liu&ensp;|&ensp;刘易
copyright-text: '&copy; Yi Liu 2024-2025. All Rights Reserved.'
